Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  config.vm.define "vandreS" do |vm|
    vm.vm.hostname = "vandreS"
    vm.vm.network "public_network",bridge: "enp0s8", ip:"192.168.56.110"


    vm.vm.provider "virtualbox" do |v|
      v.name = "vandreS"
      v.memory = 2048
      v.cpus = 2
      
    end

    vm.vm.provision "shell", path: "./server.sh"
  end
end
